config/routes.rb
Rails.application.routes.draw do

  root to: 'welcome#index'
  get 'about', to: 'welcome#about'

  devise_for :users
  
  resources :users, only: [:update, :show]
  
  resources :topics do
    resources :posts, except: [:index] do
      resources :comments, only: [:create, :destroy]
    end
  end

  resources :posts, only: [] do
    resources :comments, only: [:create, :destroy]
    resources :favorites, only: [:create, :destroy]
    post '/up-vote', to: 'votes#up_vote', as: :up_vote
    post '/down-vote', to: 'votes#down_vote', as: :down_vote
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  has_many :comments, dependent: :destroy
  has_many :votes, dependent: :destroy
  has_many :favorites, dependent: :destroy
  belongs_to :user
  belongs_to :topic

  mount_uploader :image, ImageUploader
  
  default_scope { order('rank DESC') }
  scope :visible_to, ->(user) { user ? all : joins(:topic).where('topics.public' => true) }
  
  validates :title, length: { minimum: 5 }, presence: true
  validates :body, length: { minimum: 20 }, presence: true

  after_create :create_vote

  def up_votes
    votes.where(value: 1).count
  end
  
  def down_votes
    votes.where(value: -1).count
  end
  
  def points
    votes.sum(:value)
  end

  def markdown_title
    render_as_markdown(self.title)
  end
  
  def markdown_body
    render_as_markdown(self.body)
  end

  def save_with_initial_vote
    ActiveRecord::Base.transaction do
      self.save
      create_vote
    end
  end

  def update_rank
    age_in_days = (created_at - Time.new(1970,1,1)) / (60 * 60 * 24) # 1 day in seconds
    new_rank = points + age_in_days

    update_attribute(:rank, new_rank)
  end

  private
 
  def render_as_markdown(markdown)
    renderer = Redcarpet::Render::HTML.new
    extensions = {fenced_code_blocks: true}
    redcarpet = Redcarpet::Markdown.new(renderer, extensions)
    (redcarpet.render markdown).html_safe
  end
  
  def create_vote
    unless votes.find_by_user_id self.user_id
      Vote.create(value: 1, post: self, user: self.user)
    else
      return true
    end
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @posts = policy_scope(Post)
  end

  def show
    @post = Post.find(params[:id])
    @topic = Topic.find(params[:topic_id])
    @comments = @post.comments
    @new_comment = Comment.new(post: @post)
    authorize @topic
  end

  def new
    @topic = Topic.find(params[:topic_id])
    @post = Post.new(topic: @topic)
    authorize @post
  end

  def create
    @topic = Topic.find(params[:topic_id])
    @post = current_user.posts.build(post_params)
    @post.topic = @topic
    authorize @post
    if @post.save_with_initial_vote
      flash[:notice] = "Post was saved."
      redirect_to [@topic, @post]
    else
       flash[:error] = "There was an error saving the post. Please try again."
       render :new
    end
  end

  def edit
      @topic = Topic.find(params[:topic_id])
      @post = Post.find(params[:id])
      authorize @post
  end
  
  def update
     @topic = Topic.find(params[:topic_id])
     @post = Post.find(params[:id])
     authorize @post
     @post.assign_attributes(post_params)
     if @post.save
       flash[:notice] = "Post was updated."
       redirect_to [@topic, @post]
     else
       flash[:error] = "There was an error saving the post. Please try again."
       render :edit
     end
  end
  
   def destroy
     @topic = Topic.find(params[:topic_id])
     @post = Post.find(params[:id])
     authorize @post
 
     if @post.destroy
       flash[:notice] = "\"#{@post.title}\" was deleted successfully."
       redirect_to @topic
     else
       flash[:error] = "There was an error deleting the post."
       render :show
     end
   end
  
  private

  def post_params
    params.require(:post).permit(:title, :body, :image)
  end

end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_for [topic, post] do |f| %>
  <% if post.errors.any? %>
     <div class="alert alert-danger">
       <h4>There are <%= pluralize(post.errors.count, "error") %>.</h4>
       <ul>
         <% post.errors.full_messages.each do |msg| %>
           <li><%= msg %></li>
         <% end %>
       </ul>
     </div>
   <% end %>
   <%= form_group_tag(post.errors[:title]) do %>
     <%= f.label :title %>
     <%= f.text_field :title, class: 'form-control', placeholder: "Enter post title" %>
   <% end %>
   <%= form_group_tag(post.errors[:body]) do %>
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter post body" %>
   <% end %>
   <div class="form_group">
     <%= f.label :image %>
     <%= f.file_field :image %>
     <%= f.hidden_field :image_cache %>
   </div>
   <div class="form-group">
     <%= f.submit "Save", class: 'btn btn-success' %>
   </div>
 <% end %>

app/views/posts/_post.html.erb
<div class="media">
    <div class="media-left">
         <%= render partial: 'votes/voter', locals: { post: post } %>
    </div>
    <div class="media-body">
        <h4 class="media-heading">
            <%= link_to (post.markdown_title), [post.topic, post] %>
         </h4>
         <small>
            <%= image_tag(post.user.avatar.tiny.url) if post.user.avatar? %>
            submitted <%= time_ago_in_words(post.created_at) %> ago by
            <%= post.user.name %>
            <%= post.comments.count %> Comments
         </small>
    </div>
</div>

app/views/posts/edit.html.erb
 <h1>Edit Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure the it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
   </div>
 </div>

app/views/posts/index.html.erb
<h1>All Posts</h1>
<% @posts.each do |post| %>
    <div class ="media">
        <div class ="media-body">
            <h4 class ="media-heading">
                <%= link_to post.title, post %>
            </h4>
            <small>
                submitted <%= time_ago_in_words(post.created_at) %> ago by <%= post.user.name %><br>
                <%= post.comments.count %> Comments
            </small>
        </div>
    </div>
<% end %>

app/views/posts/new.html.erb
 <h1>New Post</h1>
 
 <div class="row">
   <div class="col-md-4">
     <p>Guidelines for posts</p>
     <ul>
       <li>Make sure it rhymes.</li>
       <li>Don't use the letter "A".</li>
       <li>The incessant use of hashtags will get you banned.</li>
     </ul>
   </div>
   <div class="col-md-8">
     <%= render partial: 'form', locals: { topic: @topic, post: @post } %>
   </div>
 </div>

app/views/posts/show.html.erb
<div class="row">
  <div class='col-xs-1'>
    <%= render partial: 'votes/voter', locals: { post: @post } %>
  </div>
  <div class="col-xs-11">
    <h1><%= @post.markdown_title %>
      <small>
         <%= image_tag(@post.user.avatar.tiny.url) if @post.user.avatar? %>
         submitted <%= time_ago_in_words(@post.created_at) %> ago by
         <%= @post.user.name %>
      </small>
    </h1>
  </div>
</div>
<div class="row">
  <div class="col-xs-10">
    <%= image_tag(@post.image.url, class: 'img-thumbnail img-responsive pull-right') if @post.image? %>
    <%= @post.markdown_body %>
  </div>
  <div class="col-xs-2">
    <% if policy(@post).edit? %>
      <%= link_to "Edit", edit_topic_post_path(@topic, @post), class: 'btn btn-success btn-block' %>
    <% end %>
    <% if policy(@post).destroy? %>
      <%= link_to "Delete Post", [@topic, @post], method: :delete, class: 'btn btn-danger btn-block', data: { confirm: 'Are you sure you want to delete this post?' } %>
    <% end %>
    <div>
      <h3><%= pluralize(@post.points, 'point') %></h3>
      <small>
        <%= pluralize(@post.up_votes, 'up vote') %>
        <%= pluralize(@post.down_votes, 'down vote') %>
      </small>
    </div>
    <%= render partial: 'favorites/favorite', locals: { post: @post } %>
  </div>
</div>
<% if policy(@new_comment).show? %>
  <div class='row'>
    <div class='col-xs-10'>
      <h3>Comments</h3>
      <%= render @comments %>
    </div>
  </div>
  <div class='row'>
    <div class='col-xs-10'>
      <h4>Add a comment</h4>
      <%= render partial: 'comments/form', locals: { comment: @new_comment } %>
    </div>
  </div>
<% else %>
  <div class='row'>
    <div class='col-xs-10'>
        <h3>Comments</h3>
      <div class='alert alert-info'>
        <p>You need to be signed in to view and contribute to comments.</p>
      </div>
    </div>
  </div>
<% end %>